# Generated by Django 5.0.4 on 2024-06-24 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('matric_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('programme', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Engineering', 'Software Engineering'), ('Cyber Security', 'Cyber Security'), ('Biochemistry', 'Biochemistry'), ('Industrial Chemistry', 'Industrial Chemistry'), ('Business Administration', 'Business Administration'), ('Mass Communication', 'Mass Communication'), ('Criminology', 'Criminology'), ('Microbiology', 'Microbiology'), ('Economics', 'Economics'), ('Accounting', 'Accounting')], max_length=50)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('alpha', 1), ('omega', 2)], max_length=10)),
                ('session', models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027')], max_length=10)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('alpha', 1), ('omega', 2)], max_length=10)),
                ('session', models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027')], max_length=10)),
                ('score', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
