# Generated by Django 5.0.4 on 2024-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='cgpa',
            new_name='gpa',
        ),
    ]
